languageCode = "en-us"
title = "My New Hugo Site"
baseurl = "http://example.org/"
theme = "hyde"

[params]
  themeColor = "theme-base-0a"
  title = "Midwest Mash"
  googleAnalytics = "UA-84806134-1"
  pinterest = true
  description = "Iowa girl turned Colorado transplant. Married to my wonderful guy Nick. We have a cat, Addy, and we are getting a puppy in 3 weeks (Eek!). You HAVE to see pictures of him when he comes."