languageCode = "en-us"
title = "Midwest Mash"
baseurl = "http://midwestmash.com/"
theme = "hugo-terest"

[params]
  themeColor = "violet"
  style = "violet"
  title = "Midwest Mash"
  googleAnalytics = "UA-84806134-1"
  pinterest = true
  description = "Iowa girl turned Colorado transplant. Married to my wonderful guy Nick. We have a cat, Addy, and we are getting a puppy in 3 weeks (Eek!). You HAVE to see pictures of him when he comes."