languageCode = "en-us"
title = "Midwest Mash"
baseurl = "https://sleepy-kare-3ac017.netlify.app/"
theme = "sugar-and-spice"

[params]
  author = "Traci Dietrich"
  description = "Dishing on Food and Life from my home to yours"
  googleAnalytics = "UA-84806134-1"

  main_color = "emerald"
  accent_color = "peach"
  pinterestUrl = "https://www.pinterest.com/tgoltz/pins/"
  instagramUrl = "https://instagram.com/midwest.mash/"
  facebookUrl = "https://facebook.com/midwestmash"
  aboutMeImage = "https://midwestmash.com/wp-content/uploads/2016/10/Nick-and-Traci-All-Photos-0522.jpg"
  summary = "Iowa girl turned Colorado transplant. Self-proclaimed home chef and mama to two little boys. Exploring food and embracing motherhood daily.  For collaborations please e-mail me at traci.dietrich@gmail.com"

[permalinks]
  post = "/:title"

[menu]
  [[menu.main]]
    name = "About Me"
    url = ""
    weight = -1

  [[menu.main]]
    name = "Mom Blog"
    url = "tags/mom-blog"
    weight = 1

  [[menu.main]]
    name = "Main Dish"
    url = "tags/main-dish"
    weight = 2

  [[menu.main]]
    name = "Side Dish"
    url = "tags/side-dish"
    weight = 3

  [[menu.main]]
    name = "30 Minute Meals"
    url = "tags/30-minute-meals"
    weight = 4

  [[menu.main]]
    name = "Sandwiches"
    url = "tags/sandwiches"
    weight = 5

  [[menu.main]]
    name = "Soup"
    url = "tags/soup"
    weight = 6

  [[menu.main]]
    name = "Baked Goods"
    url = "tags/baked-goods"
    weight = 7

  [[menu.main]]
    name = "Cookies"
    url = "tags/cookies"
    weight = 8

  [[menu.main]]
    name = "Toddler Treats"
    url = "tags/toddler-treats"
    weight = 9
