backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

 # Media files will be stored in the repo under static/images/uploads
media_folder: "static/images"
 # The src attribute for uploaded media will begin with /images/uploads
public_folder: "/images"

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Authors", name: "authors", widget: "string", default: "Traci Dietrich"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "recipe" # Used in routes, e.g., /admin/collections/blog
    label: "Recipe" # Used in the UI
    folder: "content/recipe" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "recipe"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Authors", name: "authors", widget: "string", default: "Traci Dietrich"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Recipe"
        name: "recipe"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "markdown"}
          - label: "Ingredients"
            name: "recipeIngredient"
            widget: "list"
            minimize_collapsed: true
            field: {label: "Ingredient", name: "ingredient", widget: "string"}
          - label: "Instructions"
            name: "recipeInstructions"
            widget: "list"
            minimize_collapsed: true
            field: {label: "Step", name: "step", widget: "string"}
